#!/bin/bash -xe
# -x  Print commands and their arguments as they are executed.
# -e  Exit immediately if a command exits with a non-zero status.
# Source common functions between scripts and environment variables
source functions
# Create the cloudformation stack
create_stack
watch_stack_progress