#!/bin/bash -xe
# -x  Print commands and their arguments as they are executed.
# -e  Exit immediately if a command exits with a non-zero status.
echo "Started at $(date -u +%Y-%m-%dT%H:%M:%S%z)"
# Source the common script functions source Environment variables if present
source functions
# Set the trap and the exit
trap cleanup EXIT
# Test for prerquistes
test_prerequisites
# Create the stack
create_stack
# Watch stack progress
watch_stack_progress
# Get the web endpoint
TIMEOUT=30
HTTP_CODE=500
i=0
while [ $i -lt $TIMEOUT -a $HTTP_CODE -gt 200 ]; do
  i=$[$i+1]
  HTTP_CODE=`curl -o /dev/null --silent --head --write-out '%{http_code}\n' https://gitlab.$DNS_DOMAIN_NAME`
  sleep 60
done


